### ISSUE TITLE
Actions fail constantly

### ISSUE THREAD

**Issue by pavel-the-best** [open-vsx/publish-extensions#71] opened 2020-06-30 09:32 UTC

**Comment by jankeromnes** [comment] 2020-06-30 09:49
Hi @pavel-the-best! Indeed, the GitHub Action fails constantly, because a few extensions can't be published (see other open issues).

However, most of the extensions in `extensions.json` get auto-published successfully.

Please let me know if you have ideas to improve the situation. (Closing as duplicate of all other open issues.)

**Closed by jankeromnes** 2020-06-30 09:49 UTC
