### ISSUE TITLE
ms-toolsai.jupyter version 2023.3.100 is actually not 2023.3.100 (?)

### ISSUE THREAD

**Issue by xaberus** [open-vsx/publish-extensions#674] opened 2023-04-09 10:36 UTC
Compare the following:
[Open-VSX](https://open-vsx.org/api/ms-toolsai/jupyter/2023.3.100/file/ms-toolsai.jupyter-2023.3.100.vsix)
```JSON
"engines":{"vscode":"^1.76.0"},
```
[Visual Studio Marketplace](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/2023.3.1000892223/vspackage)
```JSON
"engines":{"vscode":"^1.77.0"},
```
[vscode-jupyter@2023.03.100](https://github.com/microsoft/vscode-jupyter/tree/2023.03.100)
```JSON
"engines":{"vscode":"^1.77.0"},
```

all of the above must (roughly) refer to the tag [2023.03.100](https://github.com/microsoft/vscode-jupyter/tree/2023.03.100) or a later commit. This implies that the engines field in `package.json` should be set to `"vscode": "^1.77.0"` as of commit https://github.com/microsoft/vscode-jupyter/commit/42f6c0e6062f32df4f9317790f3fe3087c4ba1fb.

This is true for the Marketplace VSIX and for a locally build VSIX from source - yet the Open-VSX contains the line `"vscode": "^1.76.0"`. (also some files in the package do not match the local build). _How is this even possible?_

As a result, the `2023.03.100` version from Open-VSX results in [strange](https://github.com/VSCodium/vscodium/issues/1460) [bugs](https://github.com/VSCodium/vscodium/issues/1466) in VSCodium (removed API proposal for python kernel kind selection).

**Comment by filiptronicek** [comment] 2023-04-09 13:25
Hey there @xaberus, thanks a lot for noticing this. The last version that we published, `2023.03.100`, does not reflect the commit you mentioned and therefore that is not yet released. We could not release new versions because of https://github.com/microsoft/vscode-jupyter/issues/13260.

**Comment by xaberus** [comment] 2023-04-09 15:24
@filiptronicek Argh, that makes sense now. I also saw the hang mentioned in https://github.com/microsoft/vscode-jupyter/issues/13260 when building by hand, but thought that it was on my end because my nodejs v18 install...
Thank you, for confirming! I thought that I was missing something :see_no_evil:

**Comment by xaberus** [comment] 2023-04-09 15:38
So the actual problem is that the build script:
- was triggered by the new tag `2023.03.100`
- ran into a timeout and failed
- the failure did not abort the pipeline
- presumably the artifact from the last build was still there and got picked up as the result of the pipeline

Am I correct?

**Comment by filiptronicek** [comment] 2023-04-09 19:39
I believe this was even simpler: the tag has been created 2 weeks ago, just after the commit we are talking about. The version in the `package.json` has most likely been there for some longer time, so the publishing script already published it incorrectly in early March.

**Comment by jeanp413** [comment] 2023-04-17 21:23
@filiptronicek it would be good if we are smarter how we check a new stable version is published in MS marketplace before doing so in openvsx, can we use `vsce show <ext_id> --json` command to get the extension info in our script before publishing? 
also jupyter uses [release branches](https://github.com/microsoft/vscode-jupyter/tree/release/release-2023.03) maybe we can add a new field in the extensions.json file to check for branches with a pattern instead of using main branch
what is the plan for the broken version `2023.3.100`?  I see there's already a `2023.3.120` so maybe just leave it broken and publish the new one?
finally the extension version no longer matches the version in MS marketplace as they add some more numbers after the version in package json (maybe a timestamp?) we can match it if we can use `vsce show <ext_id> --json` to get the exact version

**Comment by filiptronicek** [comment] 2023-04-17 22:24
Thanks @jeanp413 🙏, I agree with a lot of this and thanks for sharing `vsce show <ext_id>`! When I have time, I'll look into optimizing Jupyter and our version lookups in general, as those are sometimes not reliable indeed.

**Comment by filiptronicek** [comment] 2023-04-18 13:38
I'm for real tempted to make a different repo **just** for Jupyter because they really are nasty with versions 😄

**Comment by filiptronicek** [comment] 2023-04-18 18:21
@xaberus sorry for the long wait. Could you please check if it's alright now? I have updated the extension at `2023.3.100`.

**Comment by benz0li** [comment] 2023-04-18 18:36
> @xaberus sorry for the long wait. Could you please check if it's alright now? I have updated the extension at `2023.3.100`.

@filiptronicek I can confirm that it works now. Thank you!

**Comment by xaberus** [comment] 2023-04-18 18:36
@filiptronicek  I think it works on my end. Had to reinstall it a couple of times, though. It seems VSCodium keeps the current version cached somewhere and just reinstalling always installs the cached version. What I did was to uninstall it from VSCodium and manually install the VSIX from Open-VSX...

**Comment by filiptronicek** [comment] 2023-04-18 18:37
Thank you both!

**Comment by xaberus** [comment] 2023-04-18 18:41
@filiptronicek Thank you for the awesome support :smiley: :+1:

**Comment by filiptronicek** [comment] 2023-04-18 18:44
I'll be here if you need me ;)

closing this for now

**Comment by Mr-Spade** [comment] 2023-04-19 02:52
@filiptronicek Sorry, but I seem to be running into some issues again. Unable to install the updated 2023.3.100 version from open-vsx.

In order to easily reproduce this problem, you can go to https://open-vsx.org/extension/ms-toolsai/jupyter/2023.3.100, and then try to click the "Download" button. This seems to give an error instead of downloading the vsix file.

**Comment by Mr-Spade** [comment] 2023-04-19 03:03
Or what might happen is search for jupyter in open-vsx and select version 2023.3.100, after refresh it says "extension not found"

**Comment by benz0li** [comment] 2023-04-19 04:22
> I'll be here if you need me ;)
> 
> closing this for now

Please reopen. As @Mr-Spade pointed out, `ms-toolsai.jupyter@2023.3.100` is not available anymore.

**Comment by filiptronicek** [comment] 2023-04-19 06:45
Wow, I see, it looks like all of the files for that version on blob storage were somehow removed. We're investigating together with Eclipse.

So sorry about this, never seen this happen before.

**Comment by filiptronicek** [comment] 2023-04-19 14:35
We will try to republish again either today in the evening or tomorrow morning. Will keep this thread updated

**Comment by filiptronicek** [comment] 2023-04-20 05:29
Published again, hopefully for the last time :) 

https://open-vsx.org/extension/ms-toolsai/jupyter/2023.3.100

**Comment by filiptronicek** [comment] 2023-04-20 08:28
Let's wait a day or so to close this to not let the scenario from yesterday happen again

**Closed** 2023-05-15 15:19 UTC
Labels: bug
