### ISSUE TITLE
ms-azuretools.vscode-azureresourcegroups isn't published due to dependency

### ISSUE THREAD

**Issue by tweerwag** [open-vsx/publish-extensions#627] opened 2022-08-01 12:48 UTC
The extension ms-azuretools.vscode-azureresourcegroups isn't available on Open VSX. In the logs for the Github Action is the following:

```
ms-azuretools.vscode-azureresourcegroups: prepared from /tmp/repository/main
[FAIL] Could not process extension: {
  "extension": {
    "id": "ms-azuretools.vscode-azureresourcegroups",
    "repository": "https://github.com/Microsoft/vscode-azureresourcegroups"
  },
  "context": {
    "msVersion": "0.5.5",
    "msLastUpdated": "2022-07-27T23:04:25.103Z",
    "msInstalls": 1359432,
    "msPublisher": "ms-azuretools",
    "version": "0.5.5",
    "repo": "/tmp/repository/main",
    "ref": "0eca079ac89bfd4ea4d959962543f80390587b65"
  }
}
Error: ms-azuretools.vscode-azureresourcegroups is dependent on ms-vscode.azure-account, which has to be published to Open VSX first
    at /home/runner/work/publish-extensions/publish-extensions/publish-extension.js:158:19
[FAIL] Could not process extension: {
  "extension": {
    "id": "ms-azuretools.vscode-azureresourcegroups",
    "repository": "https://github.com/Microsoft/vscode-azureresourcegroups"
  },
  "context": {
    "msVersion": "0.5.5",
    "msLastUpdated": "2022-07-27T23:04:25.103Z",
    "msInstalls": 1359432,
    "msPublisher": "ms-azuretools",
    "version": "0.5.5",
    "repo": "/tmp/repository/main",
    "ref": "0eca079ac89bfd4ea4d959962543f80390587b65"
  }
}
```

Note that ms-vscode.azure-account is in extensions.json and is available on Open VSX.

**Comment by filiptronicek** [comment] 2022-08-01 15:01
Hey @tweerwag, thanks for raising the issue! It seems that this was caused by a regression from https://github.com/open-vsx/publish-extensions/commit/ebf169a32597f37b50a64c2f61ddec6fb5758720, which should be now fixed.

**Closed** 2022-08-01 15:00 UTC

**Comment by tweerwag** [comment] 2022-08-02 18:51
Thank you for the quick reaction and fix!
