### ISSUE TITLE
Add DuckyScriptCookbook Extension

### ISSUE THREAD

**Issue by ClaraLorenzi** [open-vsx/publish-extensions#782] opened 2024-09-05 10:43 UTC
Hi would it be possible to add the DuckyScriptCookbook[1] extension available on Microsoft Visual Studio Marketplace?

[1] https://marketplace.visualstudio.com/items?itemName=Aleff.duckyscriptcookbook

**Comment by filiptronicek** [comment] 2024-09-16 12:46
Hey there, this is a duplicate of https://github.com/open-vsx/publish-extensions/issues/781. Please reach out to the author to request the extension's publishing.

**Closed by filiptronicek** 2024-09-16 12:46 UTC
